# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [push]
default_language_version:
    python: python3.8
exclude: "lib/client"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: no-commit-to-branch
        args: [--branch, master]
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--config, pyproject.toml]
    -   id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
